### ISSUE TITLE
Extract symbols not available

### ISSUE THREAD

**Issue by sushukka** [tresacton/dspectrum#3]
Have carefully followed your video. I get the signal mapped well enough from an rtl-SDR file, but the extract symbols never becomes clickable on the context menu. I can add all the plots and export samples to file, but that's it. I attached a screenshot showing my project. Screenshot seems not to work on my Ubuntu when context menu open -> one screenshot + one bad picture from wall projected deskop.  
![20161120_012915](https://cloud.githubusercontent.com/assets/19535498/20459187/8e131c44-aec1-11e6-88a9-7ba6a954cc79.jpg)
![sth7k3 1](https://cloud.githubusercontent.com/assets/19535498/20459188/8e157d18-aec1-11e6-8acc-a8383e115928.PNG)
Inspectrum and all the requisites should be installed. I'm running Linux Mint Qiana/Ubuntu#47.

**Comment by tresacton** [comment]
Hi, you just need to right click on the bottom portion of the screen (i.e. where the green lines appeared after you selected "add derived plot" >> "amplitude") for the option to extract symbols to become available.
